
import Head from "next/head";
import CareersPage from "@/components/careers/careers";


export default function Career() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CareersPage />
        </>
    );
}