import Head from "next/head";
import Web3Page from "@/components/web3";


export default function Web3() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Web3Page />
    </>
  );
}
